# Permalinks
permalink:        pretty

# Setup
url:

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:

title:            kh0p

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Simple development, and home of talking gibberish. [`@kh0p`](http:/github.com/kh0p)

# The tags listed as entries in the sidebar
sidebar_tags:     [blog, work]

#
sidebar_works:    [web, data, econ]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/sidebar-home.jpg
color:            '#A85641'

author:
  name:           'Kamil Żak'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        defm03
  github:         kh0p

  # Setting a disqus username will enable the comment section
  disqus:         kh0p

  # This photo will be used in the about section
  photo:          /public/img/avatar.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    I'm Kamil Żak, but [@kh0p](http://github.com/kh0p) is much shorter; *meaning*
    of it is unclear due to its randomness. I'm doing mathematics, economics,
    programming, visualization, technology, graphics and general '*art*'.

    >Tu ne cede malis, sed contra audentior ito. 

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
